name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dask=2023.10.0
  - dask-expr
  - python-graphviz
  - scipy
  - matplotlib
  - pip
  - pyarrow=13
  - s3fs
  - coiled
  # JupyterLab + extensions
  - jupyterlab
  - dask-labextension
  - ipywidgets